spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/erp_core
    username: prod_user
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Auto-update schema (use with caution in prod)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: WARN
    com.learn.erp_core: INFO
